[package]
name = "correlated_time_series"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5"
csv = "1.1"
ndarray = "0.13"
ndarray-linalg = "0.13"
statrs = "0.15"
chrono = "0.4.23"